metric: LVIS
num_classes: 1203

TrainDataset:
  name: LVISDataSet
  image_dir: .
  anno_path: annotations/lvis_v1_train.json
  dataset_dir: /root/paddlejob/workspace/env_run/ws/datasets/COCO
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: LVISDataSet
  image_dir: .
  anno_path: annotations/lvis_v1_val.json
  dataset_dir: /root/paddlejob/workspace/env_run/ws/datasets/COCO
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/lvis_v1_val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /root/paddlejob/workspace/env_run/ws/datasets/COCO # if set, anno_path will be 'dataset_dir/anno_path'